/**
 * "What do you do for work?" — a pick-from-a-list alternative to free text at
 * check-in, so profession search/matching (and eventually mentor-matching,
 * see OutreachProfile's `mentor` subscribedTopic) works on a fixed
 * vocabulary instead of a hundred spellings of "Nurse." Broad enough to
 * cover the SOC major-group spread (management, healthcare, trades, etc.)
 * plus a few community-specific answers (Imam, stay-at-home parent,
 * student) that a pure occupational taxonomy wouldn't include. Sorted
 * alphabetically; the last few entries are deliberately non-occupational
 * "current status" answers, listed last so they don't get lost among an
 * alphabetized set of actual job titles.
 */
export const PROFESSIONS = [
  "Accountant",
  "Actor / Performer",
  "Actuary",
  "Administrative Assistant",
  "Aerospace Engineer",
  "Agricultural Worker",
  "Air Traffic Controller",
  "Aircraft Mechanic",
  "Architect",
  "Artist / Illustrator",
  "Athletic Trainer",
  "Attorney / Lawyer",
  "Auto Mechanic",
  "Baker",
  "Bank Teller",
  "Barber / Hairstylist",
  "Bartender",
  "Biologist",
  "Bookkeeper",
  "Bus Driver",
  "Business Owner",
  "Butcher",
  "Carpenter",
  "Cashier",
  "Chef / Cook",
  "Chemist",
  "Chiropractor",
  "Civil Engineer",
  "Cleaner / Custodian",
  "Clergy / Imam / Religious Leader",
  "Coach",
  "Computer/IT Support Specialist",
  "Construction Worker",
  "Consultant",
  "Content Creator / Influencer",
  "Correctional Officer",
  "Cosmetologist",
  "Customer Service Representative",
  "Data Analyst / Data Scientist",
  "Delivery Driver",
  "Dentist",
  "Dental Hygienist",
  "Designer (Graphic/UX/Product)",
  "Dietitian / Nutritionist",
  "Doctor / Physician",
  "Economist",
  "Electrician",
  "Elementary/Middle School Teacher",
  "Engineer (Other)",
  "Entrepreneur / Startup Founder",
  "Environmental Scientist",
  "Event Planner",
  "Executive / C-Suite",
  "Farmer / Rancher",
  "Financial Advisor",
  "Firefighter",
  "Fitness Instructor / Personal Trainer",
  "Flight Attendant",
  "Florist",
  "Food Service Worker",
  "Government Employee",
  "Graphic Designer",
  "Groundskeeper / Landscaper",
  "Hair Stylist",
  "Home Health Aide",
  "Hotel/Hospitality Staff",
  "HR Specialist",
  "HVAC Technician",
  "Insurance Agent",
  "Interior Designer",
  "Interpreter / Translator",
  "IT Manager / Systems Administrator",
  "Janitor / Custodian",
  "Journalist / Reporter",
  "Judge",
  "Lab Technician",
  "Landscaper",
  "Law Enforcement / Police Officer",
  "Lawyer / Attorney",
  "Librarian",
  "Loan Officer",
  "Machinist",
  "Management Consultant",
  "Marketing Specialist",
  "Massage Therapist",
  "Mechanic",
  "Mechanical Engineer",
  "Medical Assistant",
  "Military — Active Duty",
  "Military — Veteran",
  "Musician",
  "Nurse (RN/LPN)",
  "Nurse Practitioner",
  "Occupational Therapist",
  "Office Manager",
  "Operations Manager",
  "Optometrist",
  "Paralegal",
  "Paramedic / EMT",
  "Pastor / Priest / Rabbi",
  "Personal Trainer",
  "Pharmacist",
  "Photographer / Videographer",
  "Physical Therapist",
  "Physician Assistant",
  "Pilot",
  "Plumber",
  "Podiatrist",
  "Police Officer",
  "Politician / Elected Official",
  "Postal Worker",
  "Principal / School Administrator",
  "Product Manager",
  "Professor / University Faculty",
  "Program/Project Manager",
  "Psychologist / Therapist",
  "Public Relations Specialist",
  "Radiologic Technologist",
  "Real Estate Agent",
  "Receptionist",
  "Recruiter / HR",
  "Research Scientist",
  "Restaurant Owner/Manager",
  "Retail Associate",
  "Retail Manager",
  "Sales Representative",
  "Security Guard",
  "Skilled Trades (Other)",
  "Social Worker",
  "Software Engineer / Developer",
  "Speech-Language Pathologist",
  "Sports Coach / Referee",
  "Surgeon",
  "Surveyor",
  "Teacher (K-12)",
  "Teacher's Aide",
  "Tech Support",
  "Therapist / Counselor",
  "Tour Guide",
  "Truck Driver",
  "University Professor",
  "Urban Planner",
  "Veterinarian",
  "Video Editor / Producer",
  "Warehouse Worker",
  "Web Developer",
  "Welder",
  "Writer / Author / Editor",
  // Non-occupational answers, kept last on purpose (see file doc comment).
  "Student",
  "Stay-at-home Parent",
  "Retired",
  "Currently Between Jobs",
  "Prefer not to say",
] as const;

export type Profession = (typeof PROFESSIONS)[number];
